### ISSUE TITLE
NPM install issue

### ISSUE THREAD

**Issue by EthanSK** [algolia/docsearch-website#29] opened 2020-05-27 16:34 UTC
npm i gives npm ERR! Could not install from "plugins/my-loaders" as it does not contain a package.json file.

**Comment by s-pace** [comment] 2020-08-04 15:11
👋 @EthanSK

Thanks for raising this issue.

I will close this issue since we do not struggle with this error when installing the website. Feel free to reopen the issue with more details to reproduce it if this error is still raised on your side.

**Closed as completed by s-pace** 2020-08-04 15:11 UTC
